// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Htf.Schemas.V1.Fbs.Market
{

public enum Side : sbyte
{
  Buy = 0,
  Sell = 1,
};


}
