// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Htf.Schemas.V1.Fbs.Market
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Timestamp : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Timestamp __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Seconds { get { return __p.bb.GetLong(__p.bb_pos + 0); } }
  public int Nanos { get { return __p.bb.GetInt(__p.bb_pos + 8); } }

  public static Offset<Htf.Schemas.V1.Fbs.Market.Timestamp> CreateTimestamp(FlatBufferBuilder builder, long Seconds, int Nanos) {
    builder.Prep(8, 16);
    builder.Pad(4);
    builder.PutInt(Nanos);
    builder.PutLong(Seconds);
    return new Offset<Htf.Schemas.V1.Fbs.Market.Timestamp>(builder.Offset);
  }
};


}
